### ISSUE TITLE
[BUG] The button doesn't respond after switching account/network

### ISSUE THREAD

**Issue by Peppermint1020** [onflow/FRW-iOS#343] opened 2024-09-18 04:34 UTC
The button doesn't respond when clicked within the first 10 seconds after switching accounts/network

**Comment by jeden** [comment] 2024-11-06 03:06
@Peppermint1020 which button is not responding?

**Comment by Peppermint1020** [comment] 2024-11-06 03:17
> [@Peppermint1020](https://github.com/Peppermint1020) which button is not responding?

When I created this issue ticket, within 5 seconds of switching accounts, none of the buttons on the homepage were responsive. However, when I tested the current version, a loading effect was added to the homepage after switching accounts, and the issue no longer occurs.  

@zhouxl Could you please confirm if you've already fixed this issue?

**Comment by zhouxl** [comment] 2024-11-06 03:26
@jeden all button on first tab are not responding within the first 10 seconds after switching accounts/network, Maybe it has something to do with the system version number?

**Comment by jeden** [comment] 2024-11-06 03:48
@zhouxl 
I tested on my phone and I can't reproduce this issue, unless I am tapping the wrong buttons :-)
I repeatedly swapped main <-> linked accounts, and networks as well, then immediately pressing random button on the first tap.

What do you mean by system version number? That I should try with older iOS versions?


https://github.com/user-attachments/assets/9923befd-dadb-48ad-8695-fba2056dec3c

**Comment by lmcmz** [comment] 2024-11-07 02:10
Can't reproduce it for now, close it.

If it reproduce again, we will reopen it

**Closed as completed by lmcmz** 2024-11-07 02:10 UTC
